var simplediscs_levels = [
    {
        bkColor:"sblue",
        colors:["yellow","green","purple"]
    },
    {
        bkColor:"sblue",
        colors:["green","yellow","purple"]
    },
    {
        bkColor:"sblue",
        colors:["purple","green","yellow"]
    },
    {
        bkColor:"sblue",
        colors:["yellow","purple","green"]
    },
    {
        bkColor:"yellow",
        colors:["pink","purple","orange"]
    },
    {
        bkColor:"yellow",
        colors:["orange","pink","purple"]
    },
    {
        bkColor:"yellow",
        colors:["purple","orange","pink"]
    },
    {
        bkColor:"yellow",
        colors:["orange","purple","pink"]
    },
    {
        bkColor:"orange",
        colors:["maroon","grey","green"]
    },
    {
        bkColor:"orange",
        colors:["green","maroon","grey"]
    },
    {
        bkColor:"orange",
        colors:["grey","green","maroon"]
    },
    {
        bkColor:"orange",
        colors:["green","grey","maroon"]
    },
    {
        bkColor:"sblue",
        colors:["lighblue","dgreen","fblue"]
    },
    {
        bkColor:"sblue",
        colors:["fblue","lighblue","dgreen"]
    },
    {
        bkColor:"sblue",
        colors:["dgreen","fblue","lighblue"]
    },
    {
        bkColor:"sblue",
        colors:["lighblue","fblue","dgreen"]
    },
    {
        bkColor:"purple",
        colors:["pink","lighblue","red"]
    },
    {
        bkColor:"purple",
        colors:["red","pink","lighblue"]
    },
    {
        bkColor:"purple",
        colors:["lighblue","red","pink"]
    },
    {
        bkColor:"purple",
        colors:["lighblue","pink","red"]
    },
    {
        bkColor:"dgreen",
        colors:["grey","pink","black"]
    },
    {
        bkColor:"dgreen",
        colors:["black","grey","pink"]
    },
    {
        bkColor:"dgreen",
        colors:["pink","black","grey"]
    },
    {
        bkColor:"dgreen",
        colors:["black","pink","grey"]
    },
    {
        bkColor:"sblue",
        colors:["purple","green","yellow"]
    },
    {
        bkColor:"sblue",
        colors:["yellow","purple","green"]
    },
    {
        bkColor:"sblue",
        colors:["green","yellow","purple"]
    },
    {
        bkColor:"sblue",
        colors:["purple","yellow","green"]
    }
]